-- Catálogo amplo para TESTES de simulação visual.
-- Execute no SQL Editor após a migration principal.
-- Os itens não autorizam execução clínica. Confirme habilitação profissional,
-- registro e instruções de uso na Anvisa antes de qualquer uso real.

begin;

insert into public.aesthetic_procedures
  (name, description, regions, questions, requires_product, active)
values
  ('Toxina botulínica', 'Simulação de suavização de linhas dinâmicas. Confirmar bula, indicação e habilitação antes do uso real.', array['Frontal','Glabela','Periorbital','Nariz','Lábios e região perioral','Sorriso gengival','Mento','Masseter','Mandíbula','Pescoço'], '[{"id":"efeito","label":"Intensidade pretendida","options":["Discreta","Moderada"]},{"id":"movimento","label":"Preservar movimento natural?","options":["Sim","Parcialmente"]}]', true, true),
  ('Preenchimento com ácido hialurônico', 'Planejamento visual de contorno ou reposição de volume. Região e volume devem respeitar as instruções do produto real.', array['Lábios','Malar','Mento','Mandíbula','Nariz','Olheiras','Têmporas','Sulco nasolabial','Linhas de marionete','Região perioral','Lóbulo da orelha','Dorso das mãos'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Contorno","Projeção","Reposição de volume","Suavização"]},{"id":"efeito","label":"Intensidade pretendida","options":["Discreta","Moderada"]}]', true, true),
  ('Bioestimulação de colágeno', 'Simulação de melhora gradual de firmeza e qualidade visual da pele; sem representar resultado garantido.', array['Face','Têmporas','Malar','Região pré-auricular','Mandíbula','Mento','Pescoço','Colo','Dorso das mãos','Braços','Abdômen','Glúteos','Coxas','Joelhos'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Firmeza","Qualidade da pele","Suavização de flacidez"]},{"id":"efeito","label":"Intensidade pretendida","options":["Discreta","Moderada"]}]', true, true),
  ('Skinbooster / hidratação injetável', 'Simulação de hidratação e textura, preservando anatomia e identidade.', array['Face','Região periorbital','Região perioral','Pescoço','Colo','Dorso das mãos'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Hidratação","Textura","Linhas finas"]},{"id":"efeito","label":"Intensidade pretendida","options":["Discreta","Moderada"]}]', true, true),
  ('Fios de sustentação', 'Planejamento visual de suporte tecidual discreto, sem prometer efeito clínico.', array['Sobrancelhas','Malar','Bochechas','Sulco nasolabial','Linhas de marionete','Mandíbula','Submento','Pescoço'], '[{"id":"vetor","label":"Vetor predominante","options":["Vertical","Superolateral","Lateral"]},{"id":"efeito","label":"Intensidade pretendida","options":["Discreta","Moderada"]}]', true, true),
  ('PRP / PRF estético', 'Simulação de qualidade visual da pele ou couro cabeludo; uso sujeito a regras profissionais e sanitárias próprias.', array['Face','Região periorbital','Pescoço','Colo','Dorso das mãos','Couro cabeludo'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Qualidade da pele","Linhas finas","Aspecto capilar"]},{"id":"efeito","label":"Intensidade pretendida","options":["Discreta","Moderada"]}]', false, true),
  ('Peeling químico', 'Simulação de uniformização visual de textura e tonalidade. A profundidade clínica não é inferida pela imagem.', array['Face','Pescoço','Colo','Dorso','Braços','Mãos'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Textura","Tonalidade","Linhas finas","Marcas de acne"]},{"id":"efeito","label":"Intensidade visual","options":["Discreta","Moderada"]}]', true, true),
  ('Microagulhamento', 'Simulação visual de textura e marcas, sem reproduzir inflamação ou recuperação.', array['Face','Região periorbital','Região perioral','Pescoço','Colo','Dorso','Abdômen','Braços','Coxas','Glúteos','Couro cabeludo'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Textura","Marcas de acne","Estrias","Linhas finas","Aspecto capilar"]},{"id":"efeito","label":"Intensidade visual","options":["Discreta","Moderada"]}]', false, true),
  ('Laser fracionado ablativo', 'Simulação de renovação visual da superfície cutânea; não representa tempo de recuperação.', array['Face','Região periorbital','Região perioral','Pescoço','Colo','Dorso das mãos','Cicatriz localizada'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Textura","Marcas de acne","Linhas finas","Cicatriz"]},{"id":"efeito","label":"Intensidade visual","options":["Discreta","Moderada"]}]', false, true),
  ('Laser fracionado não ablativo', 'Simulação conservadora de textura, tonalidade e linhas finas.', array['Face','Pescoço','Colo','Dorso das mãos','Cicatriz localizada'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Textura","Tonalidade","Linhas finas","Cicatriz"]},{"id":"efeito","label":"Intensidade visual","options":["Discreta","Moderada"]}]', false, true),
  ('Luz intensa pulsada (IPL)', 'Simulação de melhora visual de alterações pigmentares ou vasculares selecionadas.', array['Face','Pescoço','Colo','Dorso das mãos','Braços','Dorso'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Tonalidade","Manchas visíveis","Vasos visíveis","Aspecto global"]},{"id":"efeito","label":"Intensidade visual","options":["Discreta","Moderada"]}]', false, true),
  ('Laser vascular', 'Simulação da redução visual de vasos aparentes, sem afirmar resposta terapêutica.', array['Face','Nariz','Bochechas','Pernas','Lesão vascular localizada'], '[{"id":"objetivo","label":"Alvo visual","options":["Vasos finos","Vermelhidão difusa","Lesão localizada"]},{"id":"efeito","label":"Intensidade visual","options":["Discreta","Moderada"]}]', false, true),
  ('Remoção de tatuagem a laser', 'Simulação de clareamento progressivo da tatuagem, preservando textura natural da pele.', array['Face','Pescoço','Tronco','Braços','Antebraços','Mãos','Coxas','Pernas','Pés'], '[{"id":"efeito","label":"Grau de clareamento simulado","options":["Discreto","Moderado","Avançado"]},{"id":"preservacao","label":"Preservar vestígio natural?","options":["Sim","Não"]}]', false, true),
  ('Depilação a laser', 'Simulação da redução visual de pelos; não representa número de sessões ou resposta biológica.', array['Face','Buço','Queixo','Pescoço','Axilas','Braços','Antebraços','Tórax','Abdômen','Costas','Virilha','Glúteos','Coxas','Pernas'], '[{"id":"efeito","label":"Redução visual pretendida","options":["Discreta","Moderada","Intensa"]}]', false, true),
  ('Radiofrequência', 'Simulação de melhora discreta de firmeza e contorno, sem previsão clínica.', array['Face','Região periorbital','Mandíbula','Submento','Pescoço','Colo','Braços','Abdômen','Glúteos','Coxas','Joelhos'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Firmeza","Contorno","Textura"]},{"id":"efeito","label":"Intensidade visual","options":["Discreta","Moderada"]}]', false, true),
  ('Radiofrequência microagulhada', 'Simulação visual de firmeza e textura combinadas.', array['Face','Região periorbital','Região perioral','Mandíbula','Submento','Pescoço','Colo','Abdômen','Braços','Coxas','Glúteos'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Firmeza","Textura","Marcas de acne","Estrias"]},{"id":"efeito","label":"Intensidade visual","options":["Discreta","Moderada"]}]', false, true),
  ('Ultrassom microfocado / macrofocado', 'Simulação conservadora de firmeza ou contorno na região escolhida.', array['Sobrancelhas','Face','Malar','Mandíbula','Submento','Pescoço','Colo','Braços','Abdômen','Flancos','Glúteos','Coxas','Joelhos'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Firmeza","Contorno","Suavização de flacidez"]},{"id":"efeito","label":"Intensidade visual","options":["Discreta","Moderada"]}]', false, true),
  ('Criolipólise', 'Simulação de alteração discreta de contorno corporal; não prevê perda de gordura.', array['Submento','Braços','Tórax lateral','Abdômen superior','Abdômen inferior','Flancos','Dorso','Glúteos','Culote','Coxas internas','Coxas externas'], '[{"id":"efeito","label":"Alteração de contorno simulada","options":["Discreta","Moderada"]},{"id":"simetria","label":"Tratamento visual","options":["Bilateral","Região isolada"]}]', false, true),
  ('Eletroestimulação muscular', 'Simulação de definição corporal discreta, sem previsão de ganho muscular.', array['Abdômen','Glúteos','Braços','Panturrilhas','Coxas'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Definição","Contorno"]},{"id":"efeito","label":"Intensidade visual","options":["Discreta","Moderada"]}]', false, true),
  ('Carboxiterapia', 'Simulação visual de textura ou contorno; indicação deve ser definida pela profissional habilitada.', array['Região periorbital','Submento','Braços','Abdômen','Flancos','Glúteos','Coxas','Joelhos','Cicatriz localizada'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Textura","Contorno","Aspecto de celulite","Cicatriz"]},{"id":"efeito","label":"Intensidade visual","options":["Discreta","Moderada"]}]', false, true),
  ('Subcisão de cicatrizes', 'Simulação de suavização visual de cicatrizes deprimidas, sem representar resposta biológica.', array['Face','Bochechas','Têmporas','Dorso','Glúteos','Coxas','Cicatriz localizada'], '[{"id":"efeito","label":"Suavização visual","options":["Discreta","Moderada"]}]', false, true),
  ('Transplante capilar', 'Planejamento visual de linha frontal e distribuição capilar, sem prever densidade clínica.', array['Linha frontal capilar','Entradas','Região temporal capilar','Região média do couro cabeludo','Coroa','Barba','Sobrancelhas'], '[{"id":"densidade","label":"Densidade visual","options":["Discreta","Moderada"]},{"id":"desenho","label":"Desenho da linha","options":["Conservador","Suavemente definido"]}]', false, true),
  ('Rinoplastia', 'Simulação prévia de proporções nasais, sem substituir análise cirúrgica presencial.', array['Dorso nasal','Ponta nasal','Base nasal','Asas nasais','Columela','Nariz completo'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Dorso","Ponta","Base","Proporção global"]},{"id":"efeito","label":"Intensidade da mudança","options":["Discreta","Moderada"]}]', false, true),
  ('Blefaroplastia', 'Simulação de contorno palpebral preservando expressão e identidade.', array['Pálpebras superiores','Pálpebras inferiores','Região periorbital'], '[{"id":"area","label":"Área planejada","options":["Superior","Inferior","Superior e inferior"]},{"id":"efeito","label":"Intensidade da mudança","options":["Discreta","Moderada"]}]', false, true),
  ('Lifting facial / ritidoplastia', 'Simulação conservadora de reposicionamento facial e cervical, sem prometer resultado cirúrgico.', array['Têmporas','Sobrancelhas','Malar','Bochechas','Sulco nasolabial','Linhas de marionete','Mandíbula','Submento','Pescoço','Face completa'], '[{"id":"area","label":"Foco principal","options":["Terço médio","Terço inferior","Face e pescoço"]},{"id":"efeito","label":"Intensidade da mudança","options":["Discreta","Moderada"]}]', false, true),
  ('Lifting de sobrancelhas', 'Simulação de reposicionamento discreto das sobrancelhas, preservando expressão.', array['Sobrancelha esquerda','Sobrancelha direita','Sobrancelhas'], '[{"id":"vetor","label":"Vetor visual","options":["Cauda lateral","Arco global"]},{"id":"efeito","label":"Elevação simulada","options":["Discreta","Moderada"]}]', false, true),
  ('Otoplastia', 'Simulação de proporção e posicionamento das orelhas.', array['Orelha esquerda','Orelha direita','Orelhas'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Projeção","Contorno","Simetria"]},{"id":"efeito","label":"Intensidade da mudança","options":["Discreta","Moderada"]}]', false, true),
  ('Lipoaspiração / lipoescultura', 'Simulação de contorno corporal; não representa volume removível ou resultado garantido.', array['Submento','Braços','Tórax','Abdômen','Flancos','Dorso','Cintura','Quadris','Glúteos','Coxas internas','Coxas externas','Joelhos','Panturrilhas'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Redução de volume","Definição","Harmonização de contorno"]},{"id":"efeito","label":"Intensidade da mudança","options":["Discreta","Moderada"]}]', false, true),
  ('Abdominoplastia', 'Simulação de contorno abdominal e excesso cutâneo aparente; não substitui avaliação cirúrgica.', array['Abdômen superior','Abdômen inferior','Abdômen completo','Cintura','Flancos'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Contorno","Excesso cutâneo aparente","Definição da cintura"]},{"id":"efeito","label":"Intensidade da mudança","options":["Discreta","Moderada"]}]', false, true),
  ('Mamoplastia de aumento', 'Simulação proporcional de volume mamário; sem definir implante ou indicação.', array['Mamas','Mama esquerda','Mama direita','Colo mamário'], '[{"id":"perfil","label":"Perfil visual","options":["Natural","Moderadamente projetado"]},{"id":"volume","label":"Aumento visual","options":["Discreto","Moderado"]}]', false, true),
  ('Mamoplastia redutora / mastopexia', 'Simulação de redução ou elevação mamária preservando proporções naturais.', array['Mamas','Mama esquerda','Mama direita','Colo mamário'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Redução","Elevação","Redução e elevação"]},{"id":"efeito","label":"Intensidade da mudança","options":["Discreta","Moderada"]}]', false, true),
  ('Gluteoplastia / remodelação glútea', 'Simulação de contorno glúteo sem definir técnica, produto ou indicação.', array['Glúteos','Glúteo esquerdo','Glúteo direito','Quadris'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Contorno","Projeção","Simetria"]},{"id":"efeito","label":"Intensidade da mudança","options":["Discreta","Moderada"]}]', false, true),
  ('Braquioplastia', 'Simulação de contorno dos braços após possível retirada de excesso cutâneo.', array['Braços','Braço esquerdo','Braço direito','Axilas'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Contorno","Excesso cutâneo aparente","Simetria"]},{"id":"efeito","label":"Intensidade da mudança","options":["Discreta","Moderada"]}]', false, true),
  ('Lifting de coxas', 'Simulação de contorno das coxas preservando anatomia corporal.', array['Coxas internas','Coxas externas','Coxa esquerda','Coxa direita','Joelhos'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Contorno","Excesso cutâneo aparente","Simetria"]},{"id":"efeito","label":"Intensidade da mudança","options":["Discreta","Moderada"]}]', false, true),
  ('Correção de ginecomastia', 'Simulação de contorno torácico masculino sem substituir avaliação clínica.', array['Tórax','Mama esquerda','Mama direita','Aréolas'], '[{"id":"objetivo","label":"Objetivo visual principal","options":["Redução de volume","Contorno","Simetria"]},{"id":"efeito","label":"Intensidade da mudança","options":["Discreta","Moderada"]}]', false, true)
on conflict (name) do update set description=excluded.description, regions=excluded.regions,
  questions=excluded.questions, requires_product=excluded.requires_product, active=true;

-- Itens genéricos de teste: substitua por marcas e apresentações reais.
with product_seed(procedure_name, name, brand, unit) as (
  values
    ('Toxina botulínica', 'Toxina botulínica tipo A — TESTE', 'Cadastrar fabricante real', 'unidades'),
    ('Preenchimento com ácido hialurônico', 'Ácido hialurônico — TESTE', 'Cadastrar fabricante real', 'mL'),
    ('Bioestimulação de colágeno', 'Hidroxiapatita de cálcio — TESTE', 'Cadastrar fabricante real', 'mL'),
    ('Bioestimulação de colágeno', 'Ácido poli-L-láctico (PLLA) — TESTE', 'Cadastrar fabricante real', 'frasco'),
    ('Skinbooster / hidratação injetável', 'Ácido hialurônico para hidratação — TESTE', 'Cadastrar fabricante real', 'mL'),
    ('Fios de sustentação', 'Fio absorvível — TESTE', 'Cadastrar fabricante real', 'unidade'),
    ('Peeling químico', 'Agente de peeling — TESTE', 'Cadastrar produto real', 'aplicação')
)
insert into public.aesthetic_products (procedure_id, name, brand, unit, active)
select p.id, s.name, s.brand, s.unit, true from product_seed s
join public.aesthetic_procedures p on p.name=s.procedure_name
on conflict (procedure_id, name, brand) do update set unit=excluded.unit, active=true;

commit;
